### ISSUE TITLE
Hope to handle interlaced video

### ISSUE THREAD

**Issue by YaboWei** [Damao/Yabo#3]
A very good tool for cur video and a very good resource for study!
But I hope it can cur interlaced video.
In mode BUF_COPY_COMPLETE, some frame not found via pkt.pts or pkt.dts, because every two packets(Top packet and Bottom packet) generate one frame.
Thanks!!

**Comment by Damao** [comment]
sorry ,this project has been terminated :(
and I don't know much about video things 
wish you good luck to find one :)
